"""init db

Revision ID: abb69b8af7d9
Revises: 
Create Date: 2025-08-02 11:23:30.273014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abb69b8af7d9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unit_of_measures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('name_alias', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('goods_exit_docs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_code', sa.String(length=128), nullable=False),
    sa.Column('creation_date_time', sa.DateTime(), nullable=True),
    sa.Column('sending_department_id', sa.Integer(), nullable=True),
    sa.Column('sending_department_name', sa.String(length=128), nullable=False),
    sa.Column('exit_reason', sa.String(length=256), nullable=True),
    sa.Column('destination', sa.String(length=128), nullable=True),
    sa.Column('address', sa.String(length=512), nullable=True),
    sa.Column('sending_user_fullname', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['sending_department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doc_code')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=128), nullable=False),
    sa.Column('last_name', sa.String(length=128), nullable=False),
    sa.Column('user_name', sa.String(length=128), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('user_roll', sa.Enum('PERSONNEL', 'SUPERVISOR', 'MANAGER', 'SUPER_ADMINISTRATOR', name='userroll'), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('approval_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('approval_process', sa.Enum('GOODS_EXIT', name='paperlessprocess'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('Approved', 'Rejected', 'Pending', name='approvalstatus'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('doc_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['doc_id'], ['goods_exit_docs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('goods_exits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.Column('sap_code', sa.String(length=16), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('unit_of_measure_id', sa.Integer(), nullable=False),
    sa.Column('goods_exit_doc_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['goods_exit_doc_id'], ['goods_exit_docs.id'], ),
    sa.ForeignKeyConstraint(['unit_of_measure_id'], ['unit_of_measures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('goods_exits')
    op.drop_table('approvals')
    op.drop_table('approval_users')
    op.drop_table('users')
    op.drop_table('goods_exit_docs')
    op.drop_table('unit_of_measures')
    op.drop_table('departments')
    # ### end Alembic commands ###
